Created Fethc function with GET, POST, DELETE
raul-2001/react-todo pull request #8
Opened 2023-12-17 15:23 UTC by raul-2001

Hello, 
Thanks for reviewing my code.
I have created some fetch data functions (with GET, POST, DELETE).
I know that I have to create a new common function and use this function. Could you explain to me how to do it? 
Thank you so much.

2023-12-21 15:08 UTC, gsiryvhb commented
@raul-2001 please note - I do not get notifications for Pull Requests unless you submit another CTD Review form -

2023-12-21 15:39 UTC, gsiryvhb requested changes
Please see comments -

2023-12-21 15:39 UTC, gsiryvhb commented on src/App.js
> +    setPostTodoList({...postTodoList, records});
@raul-2001 there is no need to maintain 2 to do lists 

When you add a record, send the post to airtable to add the record, then get your items from airtable again to refresh your list using your fetchData function

2023-12-22 03:17 UTC, raul-2001 commented
But, I have submitted CTD reveiw form for lesson_1_8.

2023-12-22 03:20 UTC, gsiryvhb commented
@raul-2001 I see it - please make the corrections listed above and I will review again

2023-12-22 04:39 UTC, raul-2001 commented
I made corrections. You can review it. Thanks as well. I apologize that I bother you with these corrections.

2023-12-25 05:07 UTC, gsiryvhb approved these changes
all good

2023-12-28 13:20 UTC, merged